fix(Dockerfile): add missing deps
`whisper-git` now depends on `python-tiktoken`, but the latter can only be found as `-git` version, leading to a `paru -S` failure:

```
error: could not find all required packages:
#13 2.117     python-tiktoken (wanted by: whisper-git)
#13 ERROR: executor failed running [/bin/sh -c paru -S whisper-git --noconfirm]: exit code: 1
```

Install it manually before building `whisper-git`.

Ref: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=whisper-git#n42
https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=whisper-git&id=f7dc5c344eca943055a2be1a0697b920f83da062